#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker-blake"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "c7853f34bf9445dc92daebd859463da2" }
]

[assets]
directory = "./public"
